### ISSUE TITLE
Slice schedulers don't work well with mine_slush

### ISSUE THREAD

**Issue by bitcoindaddy** [c00w/bitHopper#128] opened 2011-08-05 16:04 UTC
In order to use Bitcoin.cz (slush) effectively, it is necessary to start mining immediately after a new block is found to get in during the first "10 percent" of shares. The shares move fast because of the high GH/s rate of the pool so it is necessary to react fast. This worked fine on the old scheduler, but on the new slice based schedulers, enough time elapses between slices that the window of opportunity is gone. 

The code in scheduler.py - select_best_server needs to be modified to check if the slush pool is ripe for picking (lower than the .43/10 range) and choose that pool to the exclusion of all others. This needs to happen during every pass through the code and not just during reslices.

**Comment by c00w** [comment] 2011-08-05 16:42
Um select best server will default to new servers first. Like slush. The issue is it only checks once very 30 seconds. I can write in some changes though.

**Comment by bitcoindaddy** [comment] 2011-08-05 17:46
It's more obvious when using the alternate scheduler. You can wait 10 minutes or more.

**Comment by c00w** [comment] 2011-08-05 17:57
Um someone found the bug. For some reason it was using mine and penalty 4 instead of mine_slush.

**Comment by c00w** [comment] 2011-08-05 22:13
I am closing this issue. If it reappears reopen.

**Closed as completed by c00w** 2011-08-05 22:13 UTC
