### ISSUE TITLE
manually trigger mine_deepbit pools

### ISSUE THREAD

**Issue by rkozola** [c00w/bitHopper#177] opened 2011-08-11 13:39 UTC
I am missing almost every deepbit block that I see triggered in irc.  It would be useful to have a button or something on the stats webpage that would allow you to manually trigger a block/reset for pools set to mine_deepbit.

**Comment by c00w** [comment] 2011-08-31 14:32
Okay.

**Comment by c00w** [comment] 2011-09-09 16:38
I'm closing this issue as it is a duplicate of the force lp mining issue.

**Closed as completed by c00w** 2011-09-09 16:38 UTC
