### ISSUE TITLE
BUG: No JSON object could be decoded

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#403] opened 2011-09-24 02:44 UTC
I'm getting these error for lots of pools not only itzod

[04:42:58] DEBUG: Error in Long Poll itzod
Traceback (most recent call last):
  File "/home/alex/bitHopper/lp.py", line 162, in receive
    response = json.loads(body)
  File "/usr/lib/python2.6/json/**init**.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

http://pastebin.com/8ugpEcyJ

I'm not getting LP's from 5-6 pools that give this error anymore

**Comment by c00w** [comment] 2011-09-25 18:05
Um, you shouldn't be getting Lp's from these pools because they are sending invalid LP's. Not sure if we broke something or the pools are just worthless.

**Comment by paraipan** [comment] 2011-09-25 18:11
could we take into account their LP's regardless of what they send into them ? with a limit offcourse like 30 secons max from the winning LP. I get nice eff here for db & btcg if i listen lots of pools that send me lp's and adjust penalties properly

**Comment by c00w** [comment] 2011-09-25 20:40
Um, the issue is how do we distinguish a error on their end from a LP if we trigger on everything we receive...

**Comment by paraipan** [comment] 2011-09-25 20:43
um, good question, dunno assume they don't send free lp's with bogus data. If some op those that we apply the digbit remedy :P

**Comment by paraipan** [comment] 2011-09-26 20:38
i disabled pools that give this error, working fine now, we could use lots of lp's in case someone adds an dynamic lp auto adjust feature

**Comment by c00w** [comment] 2011-11-06 03:27
I'm going to close this as its a non issue currently. Some pools just send out garbage and we can't do anything about it.

**Closed as completed by c00w** 2011-11-06 03:27 UTC

**Comment by paraipan** [comment] 2011-11-06 11:09
ack c00w
