### ISSUE TITLE
Can't disable bloodys in user.cfg

### ISSUE THREAD

**Issue by echiu64** [c00w/bitHopper#114] opened 2011-08-03 23:23 UTC
"role" entry in pools.cfg prevents this.

Commit: c041123ed8db2295fc338f0b9b7b6018be927f06 to fix

**Comment by c00w** [comment] 2011-08-04 03:59
Should be fixed now.

**Comment by c00w** [comment] 2011-08-04 04:16
I'm closing this request. If the issue is still there reopen the request. I already merged a commit which fixes things.

**Closed as completed by c00w** 2011-08-04 04:16 UTC
