### ISSUE TITLE
error if a pool lags

### ISSUE THREAD

**Issue by flower1024** [c00w/bitHopper#270] opened 2011-08-24 13:17 UTC
tonight bitp.it had problems and was lagging, causes my bithopper to think that all pools do lag (it was nice to see: the other pools where delagged very fast, but after a second got lagged again) and it could not select any new pool.

so it got kind of stuck.

**Comment by c00w** [comment] 2011-08-24 17:31
Can I see a log? It should only have lagged out bitp.it and not any of the other pools

**Comment by flower1024** [comment] 2011-08-24 17:48
i just reproduced it that way:
in pools.py i changed the mine_address of bitclockers (which is hot atm) to some nonsense.

same behavior.

log is here: http://www.k1024.de/Desktop.zip

started with: python -O bitHopper.py --port 80 --scheduler OldDefaultScheduler --auth flower,XXXX> log.bh 2>log2.bh.error

**Comment by c00w** [comment] 2011-08-24 18:35
Hmmm. I'm not seeing the other pools being marked as lagged or getting delagged. However at the end it looks like it stopped serving requests. Were your miners getting starved? Because then it could be a deadlock which was solved in v0.2.3

**Comment by flower1024** [comment] 2011-08-24 18:50
with your latest push https://github.com/c00w/bitHopper/commit/2ca43e41473ac6aa7c8257c3e538dcdf10dbd2c2 had the same issue right now with kiwi pool lagging -> bitclockers lagging -> ars (started mining)

**Comment by flower1024** [comment] 2011-08-24 18:51
suddenly ALL pools lagged, but got delagged fast

**Comment by c00w** [comment] 2011-08-24 19:28
Hmmm. Is your internet connection stable? I spotted the spot in the logs where it lagged bitclockers, then kiwi, then switched to ars and it worked. This seems to be intended behavior.

**Comment by flower1024** [comment] 2011-08-24 19:34
yes it is stable. i am running several ssh connections since days without a broke (and putty is not nice when it comes to connection errors)

i think it depends on pool switch: sometimes if a pool switch happens i see getwork [] submitted to [OLD POOL]
would make sense that they are detected as lagging and set the current server as lagged?

**Comment by c00w** [comment] 2011-08-24 19:36
We don't set the current server as lagged. We set the server they talked to as lagged.

**Comment by c00w** [comment] 2011-08-25 20:41
We found the bug. This should be fixed in the current version.

**Closed as completed by c00w** 2011-08-25 20:41 UTC
